#import os
#os.system("dir /s /b >list.txt")

import re
def sentenceNumber(text_file):
    with open(text_file,'r',encoding = 'utf-8') as t:
        t_line = t.readline()
        t_lines = t_line.split(" ")
        #print(t_lines)
        #print(len(t_lines))
        result=0
        for i in t_lines:
            if '.' in i:
                #print(i)
                result = result+1
            elif '?' in i:
                #print(i)
                result = result+1
            elif '!' in i:
                #print(i)
                result = result+1
        fin_result = text_file + " 문장 수 : " + str(result)
        return fin_result
'''
with open('list.txt','r',encoding= 'utf-8') as l:
    with open('list2.txt','w',encoding= 'utf-8') as l2:
        l_lines = l.readlines()
        #print(l_lines)
        for i in l_lines:
            print(i)
            l2.write(i+'r.write(result)'+'\n')
'''
with open("sentence_number.txt", 'w', encoding = 'utf-8') as r:
    result = sentenceNumber('E3101.txt')
    r.write(result+'\n')
    result = sentenceNumber('E3103.txt')
    r.write(result+'\n')
    result = sentenceNumber('E3105.txt')
    r.write(result+'\n')
    result = sentenceNumber('E3107.txt')
    r.write(result+'\n')
    result = sentenceNumber('E3201.txt')
    r.write(result+'\n')
    result = sentenceNumber('E3203.txt')
    r.write(result+'\n')
    result = sentenceNumber('E3205.txt')
    r.write(result+'\n')
    result = sentenceNumber('E3207.txt')
    r.write(result+'\n')
    result = sentenceNumber('E401.txt')
    r.write(result+'\n')
    result = sentenceNumber('E403.txt')
    r.write(result+'\n')
    result = sentenceNumber('E405.txt')
    r.write(result+'\n')
    result = sentenceNumber('E407.txt')
    r.write(result+'\n')
    result = sentenceNumber('E409.txt')
    r.write(result+'\n')
    result = sentenceNumber('H301.txt')
    r.write(result+'\n')
    result = sentenceNumber('H302.txt')
    r.write(result+'\n')
    result = sentenceNumber('H303.txt')
    r.write(result+'\n')
    result = sentenceNumber('H305.txt')
    r.write(result+'\n')
    result = sentenceNumber('H306.txt')
    r.write(result+'\n')
    result = sentenceNumber('H307.txt')
    r.write(result+'\n')
    result = sentenceNumber('H309.txt')
    r.write(result+'\n')
    result = sentenceNumber('H310.txt')
    r.write(result+'\n')
    result = sentenceNumber('H311.txt')
    r.write(result+'\n')
    result = sentenceNumber('H313.txt')
    r.write(result+'\n')
    result = sentenceNumber('H314.txt')
    r.write(result+'\n')
    result = sentenceNumber('H315.txt')
    r.write(result+'\n')
    result = sentenceNumber('H317.txt')
    r.write(result+'\n')
    result = sentenceNumber('H318.txt')
    r.write(result+'\n')
    result = sentenceNumber('H319.txt')
    r.write(result+'\n')
    result = sentenceNumber('H321.txt')
    r.write(result+'\n')
    result = sentenceNumber('H322.txt')
    r.write(result+'\n')
    result = sentenceNumber('H323.txt')
    r.write(result+'\n')
    result = sentenceNumber('H325.txt')
    r.write(result+'\n')
    result = sentenceNumber('H326.txt')
    r.write(result+'\n')
    result = sentenceNumber('H327.txt')
    r.write(result+'\n')
    result = sentenceNumber('H403.txt')
    r.write(result+'\n')
    result = sentenceNumber('H405.txt')
    r.write(result+'\n')
    result = sentenceNumber('H406.txt')
    r.write(result+'\n')
    result = sentenceNumber('H409.txt')
    r.write(result+'\n')
    result = sentenceNumber('H411.txt')
    r.write(result+'\n')
    result = sentenceNumber('H412.txt')
    r.write(result+'\n')
    result = sentenceNumber('H415.txt')
    r.write(result+'\n')
    result = sentenceNumber('H417.txt')
    r.write(result+'\n')
    result = sentenceNumber('H421.txt')
    r.write(result+'\n')
    result = sentenceNumber('H423.txt')
    r.write(result+'\n')
    result = sentenceNumber('H426.txt')
    r.write(result+'\n')
    result = sentenceNumber('H427.txt')
    r.write(result+'\n')
    result = sentenceNumber('K301.txt')
    r.write(result+'\n')
    result = sentenceNumber('K303.txt')
    r.write(result+'\n')
    result = sentenceNumber('K305.txt')
    r.write(result+'\n')
    result = sentenceNumber('K307.txt')
    r.write(result+'\n')
    result = sentenceNumber('K309.txt')
    r.write(result+'\n')
    result = sentenceNumber('K401.txt')
    r.write(result+'\n')
    result = sentenceNumber('K403.txt')
    r.write(result+'\n')
    result = sentenceNumber('K405.txt')
    r.write(result+'\n')
    result = sentenceNumber('K407.txt')
    r.write(result+'\n')
    result = sentenceNumber('K409.txt')
    r.write(result+'\n')
    result = sentenceNumber('S3A01.txt')
    r.write(result+'\n')
    result = sentenceNumber('S3A03.txt')
    r.write(result+'\n')
    result = sentenceNumber('S3A05.txt')
    r.write(result+'\n')
    result = sentenceNumber('S3A07.txt')
    r.write(result+'\n')
    result = sentenceNumber('S3B01.txt')
    r.write(result+'\n')
    result = sentenceNumber('S3B03.txt')
    r.write(result+'\n')
    result = sentenceNumber('S3B05.txt')
    r.write(result+'\n')
    result = sentenceNumber('S3B07.txt')
    r.write(result+'\n')
    result = sentenceNumber('S4A01.txt')
    r.write(result+'\n')
    result = sentenceNumber('S4A03.txt')
    r.write(result+'\n')
    result = sentenceNumber('S4A05.txt')
    r.write(result+'\n')
    result = sentenceNumber('S4A07.txt')
    r.write(result+'\n')
    result = sentenceNumber('S4B01.txt')
    r.write(result+'\n')
    result = sentenceNumber('S4B03.txt')
    r.write(result+'\n')
    result = sentenceNumber('S4B05.txt')
    r.write(result+'\n')
    result = sentenceNumber('S4B07.txt')
    r.write(result+'\n')
