#import os
def wordNumber(text_file):
    with open(text_file,'r',encoding = 'utf-8') as t:
        t_line = t.readline()
        #print(t_line)
        t_lines = t_line.split(" ")
        result = text_file + " 음절 수 : " + str(len(t_lines)-1)
        return result

with open("word_number.txt", 'w', encoding = 'utf-8') as r:
    result = wordNumber('E3101.txt')
    r.write(result+'\n')
    result = wordNumber('E3103.txt')
    r.write(result+'\n')
    result = wordNumber('E3105.txt')
    r.write(result+'\n')
    result = wordNumber('E3107.txt')
    r.write(result+'\n')
    result = wordNumber('E3201.txt')
    r.write(result+'\n')
    result = wordNumber('E3203.txt')
    r.write(result+'\n')
    result = wordNumber('E3205.txt')
    r.write(result+'\n')
    result = wordNumber('E3207.txt')
    r.write(result+'\n')
    result = wordNumber('E401.txt')
    r.write(result+'\n')
    result = wordNumber('E403.txt')
    r.write(result+'\n')
    result = wordNumber('E405.txt')
    r.write(result+'\n')
    result = wordNumber('E407.txt')
    r.write(result+'\n')
    result = wordNumber('E409.txt')
    r.write(result+'\n')
    result = wordNumber('H301.txt')
    r.write(result+'\n')
    result = wordNumber('H302.txt')
    r.write(result+'\n')
    result = wordNumber('H303.txt')
    r.write(result+'\n')
    result = wordNumber('H305.txt')
    r.write(result+'\n')
    result = wordNumber('H306.txt')
    r.write(result+'\n')
    result = wordNumber('H307.txt')
    r.write(result+'\n')
    result = wordNumber('H309.txt')
    r.write(result+'\n')
    result = wordNumber('H310.txt')
    r.write(result+'\n')
    result = wordNumber('H311.txt')
    r.write(result+'\n')
    result = wordNumber('H313.txt')
    r.write(result+'\n')
    result = wordNumber('H314.txt')
    r.write(result+'\n')
    result = wordNumber('H315.txt')
    r.write(result+'\n')
    result = wordNumber('H317.txt')
    r.write(result+'\n')
    result = wordNumber('H318.txt')
    r.write(result+'\n')
    result = wordNumber('H319.txt')
    r.write(result+'\n')
    result = wordNumber('H321.txt')
    r.write(result+'\n')
    result = wordNumber('H322.txt')
    r.write(result+'\n')
    result = wordNumber('H323.txt')
    r.write(result+'\n')
    result = wordNumber('H325.txt')
    r.write(result+'\n')
    result = wordNumber('H326.txt')
    r.write(result+'\n')
    result = wordNumber('H327.txt')
    r.write(result+'\n')
    result = wordNumber('H403.txt')
    r.write(result+'\n')
    result = wordNumber('H405.txt')
    r.write(result+'\n')
    result = wordNumber('H406.txt')
    r.write(result+'\n')
    result = wordNumber('H409.txt')
    r.write(result+'\n')
    result = wordNumber('H411.txt')
    r.write(result+'\n')
    result = wordNumber('H412.txt')
    r.write(result+'\n')
    result = wordNumber('H415.txt')
    r.write(result+'\n')
    result = wordNumber('H417.txt')
    r.write(result+'\n')
    result = wordNumber('H421.txt')
    r.write(result+'\n')
    result = wordNumber('H423.txt')
    r.write(result+'\n')
    result = wordNumber('H426.txt')
    r.write(result+'\n')
    result = wordNumber('H427.txt')
    r.write(result+'\n')
    result = wordNumber('K301.txt')
    r.write(result+'\n')
    result = wordNumber('K303.txt')
    r.write(result+'\n')
    result = wordNumber('K305.txt')
    r.write(result+'\n')
    result = wordNumber('K307.txt')
    r.write(result+'\n')
    result = wordNumber('K309.txt')
    r.write(result+'\n')
    result = wordNumber('K401.txt')
    r.write(result+'\n')
    result = wordNumber('K403.txt')
    r.write(result+'\n')
    result = wordNumber('K405.txt')
    r.write(result+'\n')
    result = wordNumber('K407.txt')
    r.write(result+'\n')
    result = wordNumber('K409.txt')
    r.write(result+'\n')
    result = wordNumber('S3A01.txt')
    r.write(result+'\n')
    result = wordNumber('S3A03.txt')
    r.write(result+'\n')
    result = wordNumber('S3A05.txt')
    r.write(result+'\n')
    result = wordNumber('S3A07.txt')
    r.write(result+'\n')
    result = wordNumber('S3B01.txt')
    r.write(result+'\n')
    result = wordNumber('S3B03.txt')
    r.write(result+'\n')
    result = wordNumber('S3B05.txt')
    r.write(result+'\n')
    result = wordNumber('S3B07.txt')
    r.write(result+'\n')
    result = wordNumber('S4A01.txt')
    r.write(result+'\n')
    result = wordNumber('S4A03.txt')
    r.write(result+'\n')
    result = wordNumber('S4A05.txt')
    r.write(result+'\n')
    result = wordNumber('S4A07.txt')
    r.write(result+'\n')
    result = wordNumber('S4B01.txt')
    r.write(result+'\n')
    result = wordNumber('S4B03.txt')
    r.write(result+'\n')
    result = wordNumber('S4B05.txt')
    r.write(result+'\n')
    result = wordNumber('S4B07.txt')
    r.write(result+'\n')
