import re
def sentenceNumber(text_file):
    with open(text_file,'r',encoding = 'utf-8') as t:
        t_line = t.readline()
        t_lines = t_line.split(" ")
        #print(t_lines)
        #print(len(t_lines))
        result=0
        for i in t_lines:
            if '.' in i:
                #print(i)
                result = result+1
            elif '?' in i:
                #print(i)
                result = result+1
            elif '!' in i:
                #print(i)
                result = result+1
        fin_result = text_file + " 문장 수 : " + str(result)
        return fin_result


with open("sentence_number.txt", 'w', encoding = 'utf-8') as r:
    result = sentenceNumber('E3102.txt') 
    r.write(result + '\n')
    result = sentenceNumber('E3104.txt') 
    r.write(result + '\n')
    result = sentenceNumber('E3106.txt') 
    r.write(result + '\n')
    result = sentenceNumber('E3202.txt') 
    r.write(result + '\n')
    result = sentenceNumber('E3204.txt') 
    r.write(result + '\n')
    result = sentenceNumber('E3206.txt') 
    r.write(result + '\n')
    result = sentenceNumber('E402.txt') 
    r.write(result + '\n')
    result = sentenceNumber('E404.txt') 
    r.write(result + '\n')
    result = sentenceNumber('E406.txt') 
    r.write(result + '\n')
    result = sentenceNumber('E408.txt') 
    r.write(result + '\n')
    result = sentenceNumber('E410.txt') 
    r.write(result + '\n')
    result = sentenceNumber('H304.txt') 
    r.write(result + '\n')
    result = sentenceNumber('H308.txt') 
    r.write(result + '\n')
    result = sentenceNumber('H312.txt') 
    r.write(result + '\n')
    result = sentenceNumber('H316.txt') 
    r.write(result + '\n')
    result = sentenceNumber('H320.txt') 
    r.write(result + '\n')
    result = sentenceNumber('H324.txt') 
    r.write(result + '\n')
    result = sentenceNumber('H402.txt') 
    r.write(result + '\n')
    result = sentenceNumber('H408.txt') 
    r.write(result + '\n')
    result = sentenceNumber('H414.txt') 
    r.write(result + '\n')
    result = sentenceNumber('H418.txt') 
    r.write(result + '\n')
    result = sentenceNumber('H420.txt') 
    r.write(result + '\n')
    result = sentenceNumber('H424.txt') 
    r.write(result + '\n')
    result = sentenceNumber('K302.txt') 
    r.write(result + '\n')
    result = sentenceNumber('K304.txt') 
    r.write(result + '\n')
    result = sentenceNumber('k306.txt') 
    r.write(result + '\n')
    result = sentenceNumber('K308.txt') 
    r.write(result + '\n')
    result = sentenceNumber('K310.txt') 
    r.write(result + '\n')
    result = sentenceNumber('K402.txt')
    r.write(result + '\n')
    result = sentenceNumber('K404.txt') 
    r.write(result + '\n')
    result = sentenceNumber('K406.txt')
    r.write(result + '\n')
    result = sentenceNumber('K408.txt') 
    r.write(result + '\n')
    result = sentenceNumber('K410.txt')
    r.write(result + '\n')
    result = sentenceNumber('S3A02.txt') 
    r.write(result + '\n')
    result = sentenceNumber('S3A04.txt') 
    r.write(result + '\n')
    result = sentenceNumber('S3A06.txt') 
    r.write(result + '\n')
    result = sentenceNumber('S3A08.txt') 
    r.write(result + '\n')
    result = sentenceNumber('S3B02.txt') 
    r.write(result + '\n')
    result = sentenceNumber('S3B04.txt') 
    r.write(result + '\n')
    result = sentenceNumber('S3B06.txt') 
    r.write(result + '\n')
    result = sentenceNumber('S3B08.txt') 
    r.write(result + '\n')
    result = sentenceNumber('S4A02.txt') 
    r.write(result + '\n')
    result = sentenceNumber('S4A04.txt') 
    r.write(result + '\n')
    result = sentenceNumber('S4A06.txt') 
    r.write(result + '\n')
    result = sentenceNumber('S4A08.txt') 
    r.write(result + '\n')
    result = sentenceNumber('S4B02.txt') 
    r.write(result + '\n')
    result = sentenceNumber('S4B04.txt') 
    r.write(result + '\n')
    result = sentenceNumber('S4B06.txt') 
    r.write(result + '\n')
    result = sentenceNumber('S4B08.txt') 
    r.write(result + '\n')

